---
- hosts: jenkins
  become: true
  connection: ssh
  tasks:
    - name: Download Jenkins .repo
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo 
    - name: Importing Keys on jenkins
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
    - name: 'Install Jenkins'  
      yum: 
        name: jenkins
        state: latest
    - name: 'Install java'    
      yum:
        name: java
        state: lastest
    - name: "Stating Jenkins"          
      service:
        name: jenkins
        state: started
        enabled: true
